spring:
  cloud:
    stream:
      bindings:
        # === PRODUCER 바인딩 설정 ===
        errorLogProducer-out-0: # producer_1: 공통 error 로그를 수집하는 큐로 메시지 전달 (direct exchange)
          destination: error.logging.exchange         # 업계 표준: error 로그용 exchange
          content-type: application/json

        errorLogConsumer-in-0:
          destination: error.logging.exchange
          group: errorLogGroup
          content-type: application/json

#      rabbit:
#        bindings:
#          errorLogProducer-out-0:
#            producer:
#              routing-key: error.log
#              routing-key-expression: '''error.log'''
#              exchange-type: direct

          # === CONSUMER 별 RabbitMQ 세부 설정 ===
#          errorLogConsumer-in-0:
#            consumer:
#              binding-routing-key: error.log
#              exchange-type: direct
    function:
      definition: errorLogConsumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest