spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default:
        content-type: application/json
#      rabbit:
#        default:
#          producer:
#            exchangeType: direct
