spring:
  config:
    import:
      - optional:classpath:stream/application-stream_common.yml
      - optional:classpath:stream/project_crons.yml
      - optional:classpath:stream/bulk-data-transfer.yml
  cloud:
    function:
      definition: collectMessage
    stream:
      bindings:
        # === Batch 작업수행하는
        collectMessage-in-0:
          destination: message.collect
          consumer:
            batch-mode: true
      rabbit:
        bindings:
          collectMessage-in-0:
            consumer:
              exchange-type: direct
              binding-routing-key: message.collect
              enable-batching: true
              batch-size: 50
              receive-timeout: 5000